server:
  port: 9000

spring:
  application:
    name: board-article-service
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      enabled: false

resilience4j:
  retry:
    instances:
      snowflake:
        max-attempts: 3
        wait-duration: 500ms

snowflake-service:
  url: ${SNOWFLAKE_SERVICE_URL}

aws:
  xray:
    fixed-segment-name: article-service
    prefix-log-name: xray
    sampling-rules-json: /xray/xray-sampling-rules.json

    datasource:
      driver-class-name: ${DB_DRIVER_CLASS_NAME}
      jdbc-url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
#      maximum-pool-size: 10
#      minimum-idle: 2
#      connection-timeout: 30000
#      validation-timeout: 5000