server:
  port: 9000
spring:
  application:
    name: board-article-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/article
    url: ${DB_URL}
#    username: root
    username: ${DB_USERNAME}
#    password: root
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none

resilience4j:
  retry:
    instances:
      snowflake:
        max-attempts: 3
        wait-duration: 500ms

snowflake-service:
  url: ${SNOWFLAKE_SERVICE_URL}